name: Deploy API to ECR + App Runner

on:
  push:
    branches: [ "main" ]
    paths:
      - "llm_txt/**"
      - "pyproject.toml"
      - "Dockerfile.api"
      - ".github/workflows/deploy-api-ecr-apprunner.yml"
  workflow_dispatch:

permissions:
  id-token: write   # for OIDC to AWS
  contents: read

env:
  ECR_REPO: ${{ vars.ECR_REPO || 'llm-txt-api' }}
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
  APP_RUNNER_SERVICE_ARN: ${{ secrets.APP_RUNNER_SERVICE_ARN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE_URI=${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPO }}
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker build -f Dockerfile.api -t $IMAGE_URI:latest -t $IMAGE_URI:${{ github.sha }} .

      - name: Push image
        run: |
          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:${{ github.sha }}

      - name: Update App Runner service (optional)
        if: ${{ env.APP_RUNNER_SERVICE_ARN != '' }}
        run: |
          IMAGE_URI=${IMAGE_URI}:latest
          aws apprunner update-service \
            --service-arn "$APP_RUNNER_SERVICE_ARN" \
            --source-configuration "ImageRepository={ImageIdentifier=${IMAGE_URI},ImageRepositoryType=ECR},AutoDeploymentsEnabled=true"
